const DOCUMENTS_CONTENT = {
  en: {
    heading: "Ask about your own document",
    privacyNotice: "Uploaded documents are sent to an AI service to answer your questions; don't upload sensitive personal documents.",
    uploadSrLabel: "Upload a PDF document",
    dropzoneHint: "Click to upload, or drag and drop a PDF",
    dropzoneFileTypeHint: "PDF, up to 20MB",
    changeFileHint: "Click to choose a different file",
    uploading: "Reading and summarizing your document...",
    datesHeading: "Important Dates and Deadlines",
    questionSrLabel: "Ask a question about this document",
    questionPlaceholder: "Ask a question about this document...",
    askButton: "Ask",
    askingButton: "Asking...",
    noAnswerFallback: "No answer returned.",
    errUpload: "Could not upload the document. Make sure the backend server is running.",
    errAsk: "Something went wrong asking about the document.",
    errNetworkUpload: "Could not reach the server. Make sure the backend is running.",
    errNetworkAsk: "Could not reach the server. Please try again.",
    myDocsIntro: "Everything you've uploaded, generated, or saved lives here so you don't have to redo the work.",
    uploadedListHeading: "Your uploaded PDFs",
    uploadedListEmpty: "PDFs you upload above will be listed here so you can find them again.",
    uploadedOnLabel: "Uploaded",
    generatedListHeading: "Your generated documents",
    generatedListEmpty: "Documents you create in Document Generator will be listed here.",
    generatedOnLabel: "Generated",
    savedSearchesListHeading: "Your saved searches",
    savedSearchesListEmpty: "Save a search result to find it again here.",
    savedOnLabel: "Saved",
    openButton: "Open",
    downloadButton: "Download",
    deleteButton: "Delete",
    deleteConfirmYes: "Yes, delete",
    cancelButton: "Cancel",
    deleteUploadedConfirm: "Remove this from your list? This won't delete the file from your device.",
    deleteGeneratedConfirm: "Delete this generated document? This can't be undone.",
    viewInSearchButton: "Open in Search",
    reuploadHint: "If asking a question about this document doesn't work, the server may have restarted since you uploaded it — upload it again.",
    removeButton: "Remove",
    removeConfirmYes: "Yes, remove",
    closeButton: "Close",
    errStorageFull: "Storage is full. This document is available now, but couldn't be saved for your next visit. Remove older documents to free up space.",
  },
  hi: {
    heading: "अपने दस्तावेज़ के बारे में पूछें",
    privacyNotice: "अपलोड किए गए दस्तावेज़ आपके प्रश्नों के उत्तर देने के लिए एक एआई सेवा को भेजे जाते हैं; संवेदनशील व्यक्तिगत दस्तावेज़ अपलोड न करें।",
    uploadSrLabel: "पीडीएफ दस्तावेज़ अपलोड करें",
    dropzoneHint: "अपलोड करने के लिए क्लिक करें, या पीडीएफ फ़ाइल खींचकर छोड़ें",
    dropzoneFileTypeHint: "पीडीएफ, अधिकतम 20MB",
    changeFileHint: "दूसरी फ़ाइल चुनने के लिए क्लिक करें",
    uploading: "आपका दस्तावेज़ पढ़ा और सारांशित किया जा रहा है...",
    datesHeading: "महत्वपूर्ण तिथियां और समय-सीमाएं",
    questionSrLabel: "इस दस्तावेज़ के बारे में एक सवाल पूछें",
    questionPlaceholder: "इस दस्तावेज़ के बारे में एक सवाल पूछें...",
    askButton: "पूछें",
    askingButton: "पूछ रहे हैं...",
    noAnswerFallback: "कोई उत्तर नहीं मिला।",
    errUpload: "दस्तावेज़ अपलोड नहीं हो सका। सुनिश्चित करें कि बैकएंड सर्वर चल रहा है।",
    errAsk: "इस दस्तावेज़ के बारे में पूछने में कुछ गड़बड़ी हुई।",
    errNetworkUpload: "सर्वर से संपर्क नहीं हो पाया। सुनिश्चित करें कि बैकएंड चल रहा है।",
    errNetworkAsk: "सर्वर से संपर्क नहीं हो पाया। कृपया फिर से कोशिश करें।",
    myDocsIntro: "आपने जो कुछ भी अपलोड, जनरेट या सेव किया है, वह सब यहां मिलेगा, ताकि आपको दोबारा काम न करना पड़े।",
    uploadedListHeading: "आपके अपलोड किए गए पीडीएफ",
    uploadedListEmpty: "आपके द्वारा ऊपर अपलोड किए गए पीडीएफ यहां सूचीबद्ध होंगे ताकि आप उन्हें फिर से पा सकें।",
    uploadedOnLabel: "अपलोड किया गया",
    generatedListHeading: "आपके जनरेट किए गए दस्तावेज़",
    generatedListEmpty: "डॉक्यूमेंट जनरेटर में बनाए गए दस्तावेज़ यहां सूचीबद्ध होंगे।",
    generatedOnLabel: "जनरेट किया गया",
    savedSearchesListHeading: "आपकी सेव की गई खोजें",
    savedSearchesListEmpty: "किसी खोज परिणाम को सेव करें ताकि उसे यहां दोबारा पा सकें।",
    savedOnLabel: "सेव किया गया",
    openButton: "खोलें",
    downloadButton: "डाउनलोड करें",
    deleteButton: "हटाएं",
    deleteConfirmYes: "हां, हटाएं",
    cancelButton: "रद्द करें",
    deleteUploadedConfirm: "इसे अपनी सूची से हटाएं? इससे आपके डिवाइस से फ़ाइल नहीं हटेगी।",
    deleteGeneratedConfirm: "यह जनरेट किया गया दस्तावेज़ हटाएं? यह पूर्ववत नहीं किया जा सकता।",
    viewInSearchButton: "खोज में खोलें",
    reuploadHint: "अगर इस दस्तावेज़ के बारे में सवाल पूछना काम नहीं करता, तो हो सकता है आपके अपलोड करने के बाद सर्वर फिर से शुरू हुआ हो — इसे दोबारा अपलोड करें।",
    removeButton: "हटाएं",
    removeConfirmYes: "हां, हटाएं",
    closeButton: "बंद करें",
    errStorageFull: "स्टोरेज भर गया है। यह दस्तावेज़ अभी उपलब्ध है, लेकिन अगली बार के लिए सेव नहीं हो सका। जगह खाली करने के लिए पुराने दस्तावेज़ हटाएं।",
  },
  kn: {
    heading: "ನಿಮ್ಮ ದಾಖಲೆಯ ಬಗ್ಗೆ ಕೇಳಿ",
    privacyNotice: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಲು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆಗಳನ್ನು AI ಸೇವೆಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ; ಸೂಕ್ಷ್ಮ ವೈಯಕ್ತಿಕ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಬೇಡಿ.",
    uploadSrLabel: "ಪಿಡಿಎಫ್ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    dropzoneHint: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ, ಅಥವಾ ಪಿಡಿಎಫ್ ಫೈಲ್ ಅನ್ನು ಎಳೆದು ಬಿಡಿ",
    dropzoneFileTypeHint: "ಪಿಡಿಎಫ್, ಗರಿಷ್ಠ 20MB",
    changeFileHint: "ಬೇರೆ ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    uploading: "ನಿಮ್ಮ ದಾಖಲೆಯನ್ನು ಓದಿ ಸಾರಾಂಶಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    datesHeading: "ಪ್ರಮುಖ ದಿನಾಂಕಗಳು ಮತ್ತು ಗಡುವುಗಳು",
    questionSrLabel: "ಈ ದಾಖಲೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ",
    questionPlaceholder: "ಈ ದಾಖಲೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    askButton: "ಕೇಳಿ",
    askingButton: "ಕೇಳಲಾಗುತ್ತಿದೆ...",
    noAnswerFallback: "ಯಾವುದೇ ಉತ್ತರ ಸಿಗಲಿಲ್ಲ.",
    errUpload: "ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಬ್ಯಾಕೆಂಡ್ ಸರ್ವರ್ ಚಾಲನೆಯಲ್ಲಿದೆಯೇ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
    errAsk: "ಈ ದಾಖಲೆಯ ಬಗ್ಗೆ ಕೇಳುವಾಗ ಏನೋ ತೊಂದರೆಯಾಗಿದೆ.",
    errNetworkUpload: "ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಬ್ಯಾಕೆಂಡ್ ಚಾಲನೆಯಲ್ಲಿದೆಯೇ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
    errNetworkAsk: "ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    myDocsIntro: "ನೀವು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ, ರಚಿಸಿದ ಅಥವಾ ಉಳಿಸಿದ ಎಲ್ಲವೂ ಇಲ್ಲಿ ಇರುತ್ತದೆ, ಇದರಿಂದ ನೀವು ಮತ್ತೆ ಅದೇ ಕೆಲಸ ಮಾಡಬೇಕಿಲ್ಲ.",
    uploadedListHeading: "ನಿಮ್ಮ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಪಿಡಿಎಫ್‌ಗಳು",
    uploadedListEmpty: "ಮೇಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಪಿಡಿಎಫ್‌ಗಳು ಇಲ್ಲಿ ಪಟ್ಟಿಯಾಗುತ್ತವೆ, ಇದರಿಂದ ನೀವು ಅವುಗಳನ್ನು ಮತ್ತೆ ಕಂಡುಕೊಳ್ಳಬಹುದು.",
    uploadedOnLabel: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ",
    generatedListHeading: "ನಿಮ್ಮ ರಚಿಸಿದ ದಾಖಲೆಗಳು",
    generatedListEmpty: "ಡಾಕುಮೆಂಟ್ ಜನರೇಟರ್‌ನಲ್ಲಿ ರಚಿಸಿದ ದಾಖಲೆಗಳು ಇಲ್ಲಿ ಪಟ್ಟಿಯಾಗುತ್ತವೆ.",
    generatedOnLabel: "ರಚಿಸಲಾಗಿದೆ",
    savedSearchesListHeading: "ನಿಮ್ಮ ಉಳಿಸಿದ ಹುಡುಕಾಟಗಳು",
    savedSearchesListEmpty: "ಹುಡುಕಾಟ ಫಲಿತಾಂಶವನ್ನು ಉಳಿಸಿ, ಇದರಿಂದ ಅದನ್ನು ಇಲ್ಲಿ ಮತ್ತೆ ಕಂಡುಕೊಳ್ಳಬಹುದು.",
    savedOnLabel: "ಉಳಿಸಲಾಗಿದೆ",
    openButton: "ತೆರೆಯಿರಿ",
    downloadButton: "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    deleteButton: "ಅಳಿಸಿ",
    deleteConfirmYes: "ಹೌದು, ಅಳಿಸಿ",
    cancelButton: "ರದ್ದುಮಾಡಿ",
    deleteUploadedConfirm: "ಇದನ್ನು ನಿಮ್ಮ ಪಟ್ಟಿಯಿಂದ ತೆಗೆದುಹಾಕುವುದೇ? ಇದು ನಿಮ್ಮ ಸಾಧನದಿಂದ ಫೈಲ್ ಅನ್ನು ಅಳಿಸುವುದಿಲ್ಲ.",
    deleteGeneratedConfirm: "ಈ ರಚಿಸಿದ ದಾಖಲೆಯನ್ನು ಅಳಿಸುವುದೇ? ಇದನ್ನು ಹಿಂಪಡೆಯಲಾಗುವುದಿಲ್ಲ.",
    viewInSearchButton: "ಹುಡುಕಾಟದಲ್ಲಿ ತೆರೆಯಿರಿ",
    reuploadHint: "ಈ ದಾಖಲೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳುವುದು ಕೆಲಸ ಮಾಡದಿದ್ದರೆ, ನೀವು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ನಂತರ ಸರ್ವರ್ ಮರುಪ್ರಾರಂಭವಾಗಿರಬಹುದು — ಅದನ್ನು ಮತ್ತೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    removeButton: "ತೆಗೆದುಹಾಕಿ",
    removeConfirmYes: "ಹೌದು, ತೆಗೆದುಹಾಕಿ",
    closeButton: "ಮುಚ್ಚಿ",
    errStorageFull: "ಸಂಗ್ರಹಣೆ ಭರ್ತಿಯಾಗಿದೆ. ಈ ದಾಖಲೆ ಈಗ ಲಭ್ಯವಿದೆ, ಆದರೆ ಮುಂದಿನ ಭೇಟಿಗಾಗಿ ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಸ್ಥಳಾವಕಾಶ ಮಾಡಲು ಹಳೆಯ ದಾಖಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.",
  },
};

export function getDocumentsContent(uiLanguage) {
  return DOCUMENTS_CONTENT[uiLanguage] || DOCUMENTS_CONTENT.en;
}
