rewrite_validation_set = [
    ("How long can police hold me before bringing me to court?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "58"),
    ("Can police arrest me just to stop me committing a crime?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "170"),
    ("Can a court give emergency protection before hearing both sides?", "Protection of Women from Domestic Violence Act, 2005", "23"),
    ("What counts as sexual harassment under the law?", "Bharatiya Nyaya Sanhita, 2023", "75"),
    ("What legally counts as cruelty in marriage?", "Bharatiya Nyaya Sanhita, 2023", "86"),
    ("What's the punishment for taking a bribe?", "Bharatiya Nyaya Sanhita, 2023", "170"),
    ("What if I accidentally kill the wrong person while trying to kill someone else?", "Bharatiya Nyaya Sanhita, 2023", "102"),
    ("Can consumer disputes be settled through mediation?", "Consumer Protection Act, 2019", "79"),
    ("Can police force someone to come in as a witness?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "179"),
    ("Can seized property be sold before the case ends?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "88"),
    ("Is it illegal to sell a fake medicine as something else?", "Bharatiya Nyaya Sanhita, 2023", "278"),
    ("Do police have to get me medically checked after arrest?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "53"),
    ("What happens to evidence after the trial ends?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "498"),
    ("Is it a crime to secretly bury a baby's body to hide its birth?", "Bharatiya Nyaya Sanhita, 2023", "94"),
    ("Can an official be punished for not arresting someone they should have?", "Bharatiya Nyaya Sanhita, 2023", "264"),
    ("Can my landlord cut off my water or electricity?", "Karnataka Rent Act, 1999", "49"),
    ("What's the punishment for attacking someone to stop them doing their government job?", "Bharatiya Nyaya Sanhita, 2023", "132"),
    ("What's the punishment for encouraging a child to end their life?", "Bharatiya Nyaya Sanhita, 2023", "107"),
    ("Can police confiscate a weapon I'm carrying?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "50"),
    ("Can my car be seized if it's not registered?", "Motor Vehicles Act, 1988", "207"),
    ("Can I cancel a deal I was pressured into?", "Indian Contract Act, 1872", "19A"),
    ("Can I force someone to personally perform a service they promised?", "Specific Relief Act, 1963", "14"),
    ("How do I get a permit to run a bus service?", "Motor Vehicles Act, 1988", "72"),
    ("Can the government charge fees for vehicle-related services?", "Motor Vehicles Act, 1988", "211"),
    ("Is it illegal to create a fake document?", "Bharatiya Nyaya Sanhita, 2023", "335"),
    ("What happens if I refuse to follow a traffic officer's orders?", "Motor Vehicles Act, 1988", "179"),
    ("Can the person on trial testify in their own defense?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "353"),
    ("Do I have to follow a court order addressed to me?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "154"),
    ("Do I get to choose how I claim compensation after an accident?", "Motor Vehicles Act, 1988", "167"),
    ("Can I get bail for a cybercrime with a 3-year sentence?", "Information Technology Act, 2000", "77B"),
    ("Does the consumer authority have its own investigators?", "Consumer Protection Act, 2019", "15"),
    ("What can an appeals court actually do with my case?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "427"),
    ("Can I appeal if the court won't give my seized property back?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "89"),
    ("Can the Supreme Court move my case to a different court?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "446"),
    ("What happens if I let someone mix my goods with theirs?", "Indian Contract Act, 1872", "155"),
    ("Do small mistakes in my case automatically cancel the trial?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "506"),
    ("Do I have a special right to appeal in some situations?", "Bharatiya Nagarik Suraksha Sanhita, 2023", "421"),
    ("Can I appeal if my bus conductor's licence is refused?", "Motor Vehicles Act, 1988", "33"),
    ("Does this law replace other legal protections I have?", "Protection of Women from Domestic Violence Act, 2005", "36"),
    ("Is it illegal to habitually deal in slaves?", "Bharatiya Nyaya Sanhita, 2023", "145"),
]

import json
with open("../data/eval/rewrite_validation_set.json", "w", encoding="utf-8") as f:
    json.dump(rewrite_validation_set, f, indent=2)
print(f"Saved {len(rewrite_validation_set)} queries")
